#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/lge/joan-common

PRODUCT_COPY_FILES += \
    vendor/lge/joan-common/proprietary/system_ext/etc/dpm/dpm.conf:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/dpm/dpm.conf \
    vendor/lge/joan-common/proprietary/system_ext/etc/init/dpmd.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/dpmd.rc \
    vendor/lge/joan-common/proprietary/system_ext/etc/permissions/com.qti.dpmframework.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.qti.dpmframework.xml \
    vendor/lge/joan-common/proprietary/system_ext/etc/permissions/dpmapi.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/dpmapi.xml \
    vendor/lge/joan-common/proprietary/system_ext/etc/permissions/qcrilhook.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qcrilhook.xml \
    vendor/lge/joan-common/proprietary/system_ext/etc/permissions/qti_libpermissions.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qti_libpermissions.xml \
    vendor/lge/joan-common/proprietary/system_ext/etc/permissions/qti_permissions.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qti_permissions.xml \
    vendor/lge/joan-common/proprietary/vendor/etc/acdbdata/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Bluetooth_cal.acdb \
    vendor/lge/joan-common/proprietary/vendor/etc/acdbdata/Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Codec_cal.acdb \
    vendor/lge/joan-common/proprietary/vendor/etc/acdbdata/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/General_cal.acdb \
    vendor/lge/joan-common/proprietary/vendor/etc/acdbdata/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Global_cal.acdb \
    vendor/lge/joan-common/proprietary/vendor/etc/acdbdata/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Handset_cal.acdb \
    vendor/lge/joan-common/proprietary/vendor/etc/acdbdata/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Hdmi_cal.acdb \
    vendor/lge/joan-common/proprietary/vendor/etc/acdbdata/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Headset_cal.acdb \
    vendor/lge/joan-common/proprietary/vendor/etc/acdbdata/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Speaker_cal.acdb \
    vendor/lge/joan-common/proprietary/vendor/etc/acdbdata/adsp_avs_config.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/adsp_avs_config.acdb \
    vendor/lge/joan-common/proprietary/vendor/etc/cacert_location.pem:$(TARGET_COPY_OUT_VENDOR)/etc/cacert_location.pem \
    vendor/lge/joan-common/proprietary/vendor/etc/camera/bu24235_dl_program_Joan_LGITAct_ICG1020S_rev0_S_data1.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/bu24235_dl_program_Joan_LGITAct_ICG1020S_rev0_S_data1.bin \
    vendor/lge/joan-common/proprietary/vendor/etc/camera/bu24235_dl_program_Joan_LGITAct_ICG1020S_rev0_S_data2.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/bu24235_dl_program_Joan_LGITAct_ICG1020S_rev0_S_data2.bin \
    vendor/lge/joan-common/proprietary/vendor/etc/camera/bu24235_dl_program_Joan_LGITAct_ICG1020S_rev3_S_data1.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/bu24235_dl_program_Joan_LGITAct_ICG1020S_rev3_S_data1.bin \
    vendor/lge/joan-common/proprietary/vendor/etc/camera/bu24235_dl_program_Joan_LGITAct_ICG1020S_rev3_S_data2.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/bu24235_dl_program_Joan_LGITAct_ICG1020S_rev3_S_data2.bin \
    vendor/lge/joan-common/proprietary/vendor/etc/camera/bu24235_dl_program_Joan_LGITAct_ICG1020S_rev5_S_data1.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/bu24235_dl_program_Joan_LGITAct_ICG1020S_rev5_S_data1.bin \
    vendor/lge/joan-common/proprietary/vendor/etc/camera/bu24235_dl_program_Joan_LGITAct_ICG1020S_rev5_S_data2.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/bu24235_dl_program_Joan_LGITAct_ICG1020S_rev5_S_data2.bin \
    vendor/lge/joan-common/proprietary/vendor/etc/cne/mwqem.conf:$(TARGET_COPY_OUT_VENDOR)/etc/cne/mwqem.conf \
    vendor/lge/joan-common/proprietary/vendor/etc/cne/profileMwqem.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/profileMwqem.xml \
    vendor/lge/joan-common/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile1.xml \
    vendor/lge/joan-common/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile2.xml \
    vendor/lge/joan-common/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile3.xml \
    vendor/lge/joan-common/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile4.xml \
    vendor/lge/joan-common/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile5.xml \
    vendor/lge/joan-common/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile6.xml \
    vendor/lge/joan-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile1.xml \
    vendor/lge/joan-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile15.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile15.xml \
    vendor/lge/joan-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile16.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile16.xml \
    vendor/lge/joan-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile17.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile17.xml \
    vendor/lge/joan-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile18.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile18.xml \
    vendor/lge/joan-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile19.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile19.xml \
    vendor/lge/joan-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile2.xml \
    vendor/lge/joan-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile20.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile20.xml \
    vendor/lge/joan-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile21.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile21.xml \
    vendor/lge/joan-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile3.xml \
    vendor/lge/joan-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile32.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile32.xml \
    vendor/lge/joan-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile4.xml \
    vendor/lge/joan-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile5.xml \
    vendor/lge/joan-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile6.xml \
    vendor/lge/joan-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile7.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile7.xml \
    vendor/lge/joan-common/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile1.xml \
    vendor/lge/joan-common/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile2.xml \
    vendor/lge/joan-common/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile3.xml \
    vendor/lge/joan-common/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile4.xml \
    vendor/lge/joan-common/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile5.xml \
    vendor/lge/joan-common/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile6.xml \
    vendor/lge/joan-common/proprietary/vendor/etc/data/dsi_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/dsi_config.xml \
    vendor/lge/joan-common/proprietary/vendor/etc/data/netmgr_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/netmgr_config.xml \
    vendor/lge/joan-common/proprietary/vendor/etc/firmware/nvm_tlv.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvm_tlv.bin \
    vendor/lge/joan-common/proprietary/vendor/etc/firmware/nvm_tlv_1.3.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvm_tlv_1.3.bin \
    vendor/lge/joan-common/proprietary/vendor/etc/firmware/nvm_tlv_2.1.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvm_tlv_2.1.bin \
    vendor/lge/joan-common/proprietary/vendor/etc/firmware/nvm_tlv_3.0.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvm_tlv_3.0.bin \
    vendor/lge/joan-common/proprietary/vendor/etc/firmware/nvm_tlv_3.2.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvm_tlv_3.2.bin \
    vendor/lge/joan-common/proprietary/vendor/etc/firmware/rampatch_tlv.img:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rampatch_tlv.img \
    vendor/lge/joan-common/proprietary/vendor/etc/firmware/rampatch_tlv_1.3.tlv:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rampatch_tlv_1.3.tlv \
    vendor/lge/joan-common/proprietary/vendor/etc/firmware/rampatch_tlv_2.1.tlv:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rampatch_tlv_2.1.tlv \
    vendor/lge/joan-common/proprietary/vendor/etc/firmware/rampatch_tlv_3.0.tlv:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rampatch_tlv_3.0.tlv \
    vendor/lge/joan-common/proprietary/vendor/etc/firmware/rampatch_tlv_3.2.tlv:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/rampatch_tlv_3.2.tlv \
    vendor/lge/joan-common/proprietary/vendor/etc/hbtp/loader.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/hbtp/loader.cfg \
    vendor/lge/joan-common/proprietary/vendor/etc/hbtp/qtc800h.bin:$(TARGET_COPY_OUT_VENDOR)/etc/hbtp/qtc800h.bin \
    vendor/lge/joan-common/proprietary/vendor/etc/hbtp/qtc800h_8998_660.bin:$(TARGET_COPY_OUT_VENDOR)/etc/hbtp/qtc800h_8998_660.bin \
    vendor/lge/joan-common/proprietary/vendor/etc/hbtp/qtc800s_dsp.bin:$(TARGET_COPY_OUT_VENDOR)/etc/hbtp/qtc800s_dsp.bin \
    vendor/lge/joan-common/proprietary/vendor/etc/hbtp/qtc800t.bin:$(TARGET_COPY_OUT_VENDOR)/etc/hbtp/qtc800t.bin \
    vendor/lge/joan-common/proprietary/vendor/etc/init/android.hardware.bluetooth@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.0-service-qti.rc \
    vendor/lge/joan-common/proprietary/vendor/etc/init/android.hardware.drm@1.3-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.3-service.widevine.rc \
    vendor/lge/joan-common/proprietary/vendor/etc/init/cnd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/cnd.rc \
    vendor/lge/joan-common/proprietary/vendor/etc/init/dataadpl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dataadpl.rc \
    vendor/lge/joan-common/proprietary/vendor/etc/init/dataqti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dataqti.rc \
    vendor/lge/joan-common/proprietary/vendor/etc/init/dpmQmiMgr.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dpmQmiMgr.rc \
    vendor/lge/joan-common/proprietary/vendor/etc/init/netmgrd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/netmgrd.rc \
    vendor/lge/joan-common/proprietary/vendor/etc/init/qcrild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qcrild.rc \
    vendor/lge/joan-common/proprietary/vendor/etc/init/vendor.display.color@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.display.color@1.0-service.rc \
    vendor/lge/joan-common/proprietary/vendor/etc/init/vendor.lge.hardware.biometrics.fingerprint@2.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.lge.hardware.biometrics.fingerprint@2.1-service.rc \
    vendor/lge/joan-common/proprietary/vendor/etc/init/vendor.qti.esepowermanager@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.esepowermanager@1.1-service.rc \
    vendor/lge/joan-common/proprietary/vendor/etc/init/vendor.qti.hardware.alarm@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.alarm@1.0-service.rc \
    vendor/lge/joan-common/proprietary/vendor/etc/init/vendor.qti.hardware.qseecom@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.qseecom@1.0-service.rc \
    vendor/lge/joan-common/proprietary/vendor/etc/init/vendor.qti.hardware.qteeconnector@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.qteeconnector@1.0-service.rc \
    vendor/lge/joan-common/proprietary/vendor/etc/init/vendor.qti.hardware.soter@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.soter@1.0-service.rc \
    vendor/lge/joan-common/proprietary/vendor/etc/init/vendor.qti.hardware.tui_comm@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.tui_comm@1.0-service-qti.rc \
    vendor/lge/joan-common/proprietary/vendor/etc/init/vendor.qti.rmt_storage.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.rmt_storage.rc \
    vendor/lge/joan-common/proprietary/vendor/etc/init/vendor.qti.tftp.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.tftp.rc \
    vendor/lge/joan-common/proprietary/vendor/etc/izat.conf:$(TARGET_COPY_OUT_VENDOR)/etc/izat.conf \
    vendor/lge/joan-common/proprietary/vendor/etc/lowi.conf:$(TARGET_COPY_OUT_VENDOR)/etc/lowi.conf \
    vendor/lge/joan-common/proprietary/vendor/etc/qdcm_calib_data_SW43402_cmd_mode_dsc_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_SW43402_cmd_mode_dsc_dsi_panel.xml \
    vendor/lge/joan-common/proprietary/vendor/etc/sap.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sap.conf \
    vendor/lge/joan-common/proprietary/vendor/etc/scve/facereco/gModel.dat:$(TARGET_COPY_OUT_VENDOR)/etc/scve/facereco/gModel.dat \
    vendor/lge/joan-common/proprietary/vendor/etc/thermal-engine-8998.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-8998.conf \
    vendor/lge/joan-common/proprietary/vendor/etc/thermal-engine-default.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-default.conf \
    vendor/lge/joan-common/proprietary/vendor/etc/thermal-engine.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine.conf \
    vendor/lge/joan-common/proprietary/vendor/etc/xtra_root_cert.pem:$(TARGET_COPY_OUT_VENDOR)/etc/xtra_root_cert.pem \
    vendor/lge/joan-common/proprietary/vendor/etc/xtwifi.conf:$(TARGET_COPY_OUT_VENDOR)/etc/xtwifi.conf \
    vendor/lge/joan-common/proprietary/vendor/firmware/Tfa9872.cnt:$(TARGET_COPY_OUT_VENDOR)/firmware/Tfa9872.cnt \
    vendor/lge/joan-common/proprietary/vendor/firmware/a530_gpmu.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_gpmu.fw2 \
    vendor/lge/joan-common/proprietary/vendor/firmware/a530_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pfp.fw \
    vendor/lge/joan-common/proprietary/vendor/firmware/a530_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pm4.fw \
    vendor/lge/joan-common/proprietary/vendor/firmware/a530_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_zap.b00 \
    vendor/lge/joan-common/proprietary/vendor/firmware/a530_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_zap.b01 \
    vendor/lge/joan-common/proprietary/vendor/firmware/a530_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_zap.b02 \
    vendor/lge/joan-common/proprietary/vendor/firmware/a530_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_zap.elf \
    vendor/lge/joan-common/proprietary/vendor/firmware/a530_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_zap.mdt \
    vendor/lge/joan-common/proprietary/vendor/firmware/a530v1_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v1_pfp.fw \
    vendor/lge/joan-common/proprietary/vendor/firmware/a530v1_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v1_pm4.fw \
    vendor/lge/joan-common/proprietary/vendor/firmware/a530v2_seq.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v2_seq.fw2 \
    vendor/lge/joan-common/proprietary/vendor/firmware/a530v3_gpmu.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v3_gpmu.fw2 \
    vendor/lge/joan-common/proprietary/vendor/firmware/a530v3_seq.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v3_seq.fw2 \
    vendor/lge/joan-common/proprietary/vendor/firmware/a540_gpmu.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_gpmu.fw2 \
    vendor/lge/joan-common/proprietary/vendor/firmware/cpp_firmware_v1_10_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_10_0.fw \
    vendor/lge/joan-common/proprietary/vendor/firmware/cpp_firmware_v1_12_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_12_0.fw \
    vendor/lge/joan-common/proprietary/vendor/firmware/cpp_firmware_v1_1_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_1.fw \
    vendor/lge/joan-common/proprietary/vendor/firmware/cpp_firmware_v1_1_6.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_6.fw \
    vendor/lge/joan-common/proprietary/vendor/firmware/cpp_firmware_v1_2_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_2_0.fw \
    vendor/lge/joan-common/proprietary/vendor/firmware/cpp_firmware_v1_4_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_4_0.fw \
    vendor/lge/joan-common/proprietary/vendor/firmware/cpp_firmware_v1_5_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_0.fw \
    vendor/lge/joan-common/proprietary/vendor/firmware/cpp_firmware_v1_5_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_1.fw \
    vendor/lge/joan-common/proprietary/vendor/firmware/cpp_firmware_v1_5_2.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_2.fw \
    vendor/lge/joan-common/proprietary/vendor/firmware/cpp_firmware_v1_6_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_6_0.fw \
    vendor/lge/joan-common/proprietary/vendor/firmware/cpp_firmware_v1_8_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_8_0.fw \
    vendor/lge/joan-common/proprietary/vendor/firmware/crbtfw21.tlv:$(TARGET_COPY_OUT_VENDOR)/firmware/crbtfw21.tlv \
    vendor/lge/joan-common/proprietary/vendor/firmware/crnv21.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/crnv21.bin \
    vendor/lge/joan-common/proprietary/vendor/firmware/leia_pfp_470.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/leia_pfp_470.fw \
    vendor/lge/joan-common/proprietary/vendor/firmware/leia_pm4_470.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/leia_pm4_470.fw \
    vendor/lge/joan-common/proprietary/vendor/radio/qcril_database/qcril.db:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/qcril.db \
    vendor/lge/joan-common/proprietary/vendor/radio/qcril_database/upgrade/0_initial.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/0_initial.sql \
    vendor/lge/joan-common/proprietary/vendor/radio/qcril_database/upgrade/10_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/10_version_update_ecc_table.sql \
    vendor/lge/joan-common/proprietary/vendor/radio/qcril_database/upgrade/1_version_intro.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/1_version_intro.sql \
    vendor/lge/joan-common/proprietary/vendor/radio/qcril_database/upgrade/2_version_add_wps_config.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/2_version_add_wps_config.sql \
    vendor/lge/joan-common/proprietary/vendor/radio/qcril_database/upgrade/3_version_update_wps_config.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/3_version_update_wps_config.sql \
    vendor/lge/joan-common/proprietary/vendor/radio/qcril_database/upgrade/4_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/4_version_update_ecc_table.sql \
    vendor/lge/joan-common/proprietary/vendor/radio/qcril_database/upgrade/5_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/5_version_update_ecc_table.sql \
    vendor/lge/joan-common/proprietary/vendor/radio/qcril_database/upgrade/6_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/6_version_update_ecc_table.sql \
    vendor/lge/joan-common/proprietary/vendor/radio/qcril_database/upgrade/7_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/7_version_update_ecc_table.sql \
    vendor/lge/joan-common/proprietary/vendor/radio/qcril_database/upgrade/8_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/8_version_update_ecc_table.sql \
    vendor/lge/joan-common/proprietary/vendor/radio/qcril_database/upgrade/9_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/9_version_update_ecc_table.sql

PRODUCT_PACKAGES += \
    eglSubDriverAndroid \
    libEGL_adreno \
    libGLESv1_CM_adreno \
    libGLESv2_adreno \
    libQTapGLES \
    libq3dtools_adreno \
    libq3dtools_esx \
    activity_recognition.msm8998 \
    sound_trigger.primary.msm8998 \
    libC2D2 \
    libOpenCL \
    libacdb-fts \
    libacdbloader \
    libacdbrtac \
    libadiertac \
    libadreno_utils \
    libadsp_default_listener \
    libadsprpc \
    libaudcal \
    libaudio_log_utils \
    libaudioalsa \
    libaudioparsers \
    libc2d30_bltlib \
    libcdsp_default_listener \
    libcdsprpc \
    libdiag \
    libdsutils \
    libfastcvopt \
    libfastrpc_utf_stub \
    libgcs-calwrapper \
    libgcs-ipc \
    libgcs-osal \
    libgcs \
    libgsl \
    libidl \
    libllvm-glnext \
    libmdmdetect \
    libmdsprpc \
    libmmcamera2_frame_algorithm \
    libmmcamera2_is \
    libmmcamera2_stats_algorithm \
    libmmcamera2_stats_lib \
    libmmcamera_dbg \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmmcamera_tintless_algo \
    libmmcamera_tintless_bg_pca_algo \
    libmmosal \
    libqdi \
    libqdp \
    libqmi \
    libqmi_cci \
    libqmi_client_helper \
    libqmi_client_qmux \
    libqmi_common_so \
    libqmi_csi \
    libqmi_encdec \
    libqmiservices \
    libqtigef \
    libsdm-disp-vndapis \
    libsdsprpc \
    libsensor1 \
    libsensor_reg \
    libsns_low_lat_stream_stub \
    libssc_default_listener \
    libthermalclient \
    libtime_genoff \
    libvpphvx \
    sensor_calibrate \
    sensors.ssc \
    libasphere \
    vendor.qti.hardware.dsp@1.0 \
    camera.msm8998 \
    libAutoContrast \
    libCB \
    libSJFingerDetect \
    libSJVideoNR \
    libactuator_bu24333gwl \
    libactuator_renesascl \
    libadm \
    libadpcmdec \
    libarcsoft_beauty_picselfie \
    libarcsoft_object_tracking \
    libarcsoft_picselfie_algorithm \
    libbwfocuspeaking \
    libchromatix_hi553_3a_face_unlock \
    libchromatix_hi553_3a_vt \
    libchromatix_hi553_4k_preview_3a \
    libchromatix_hi553_4k_video_3a \
    libchromatix_hi553_common \
    libchromatix_hi553_cpp_face_unlock \
    libchromatix_hi553_cpp_liveshot \
    libchromatix_hi553_cpp_preview \
    libchromatix_hi553_cpp_preview_lgapp \
    libchromatix_hi553_cpp_snapshot \
    libchromatix_hi553_cpp_snapshot_lgapp \
    libchromatix_hi553_cpp_video \
    libchromatix_hi553_cpp_vt \
    libchromatix_hi553_default_preview \
    libchromatix_hi553_default_video \
    libchromatix_hi553_face_unlock \
    libchromatix_hi553_isp_vt \
    libchromatix_hi553_postproc \
    libchromatix_hi553_preview \
    libchromatix_hi553_snapshot \
    libchromatix_hi553_snapshot_lgapp \
    libchromatix_hi553_video \
    libchromatix_hi553_zsl_preview \
    libchromatix_hi553_zsl_video \
    libchromatix_imx351_4k_preview_3a \
    libchromatix_imx351_4k_video_3a \
    libchromatix_imx351_binning_4k_3a \
    libchromatix_imx351_binning_video_3a \
    libchromatix_imx351_binning_zsl_3a \
    libchromatix_imx351_cinema_log \
    libchromatix_imx351_cinema_log_cpp \
    libchromatix_imx351_cinema_look \
    libchromatix_imx351_cinema_look_cpp \
    libchromatix_imx351_common \
    libchromatix_imx351_common_cinema \
    libchromatix_imx351_cpp_hd \
    libchromatix_imx351_cpp_hfr_120 \
    libchromatix_imx351_cpp_hfr_240 \
    libchromatix_imx351_cpp_hfr_60 \
    libchromatix_imx351_cpp_liveshot \
    libchromatix_imx351_cpp_liveshot_raw_hdr \
    libchromatix_imx351_cpp_preview \
    libchromatix_imx351_cpp_preview_binning \
    libchromatix_imx351_cpp_snapshot \
    libchromatix_imx351_cpp_snapshot_binning \
    libchromatix_imx351_cpp_snapshot_raw_hdr \
    libchromatix_imx351_cpp_video \
    libchromatix_imx351_cpp_video_4k \
    libchromatix_imx351_cpp_video_binning \
    libchromatix_imx351_default_preview_3a \
    libchromatix_imx351_default_video \
    libchromatix_imx351_default_video_3a \
    libchromatix_imx351_flash_food_cpp \
    libchromatix_imx351_flash_snapshot_cpp \
    libchromatix_imx351_food_preview \
    libchromatix_imx351_food_preview_cpp \
    libchromatix_imx351_food_snapshot \
    libchromatix_imx351_food_snapshot_cpp \
    libchromatix_imx351_hd \
    libchromatix_imx351_hd_3a \
    libchromatix_imx351_hfr_120 \
    libchromatix_imx351_hfr_120_3a \
    libchromatix_imx351_hfr_240 \
    libchromatix_imx351_hfr_240_3a \
    libchromatix_imx351_hfr_60 \
    libchromatix_imx351_hfr_60_3a \
    libchromatix_imx351_hfr_90_3a \
    libchromatix_imx351_panorama_cpp \
    libchromatix_imx351_panorama_preview_3a \
    libchromatix_imx351_postproc \
    libchromatix_imx351_preview \
    libchromatix_imx351_preview_raw_hdr_3a \
    libchromatix_imx351_preview_raw_hdr_3a_cinema \
    libchromatix_imx351_snapshot \
    libchromatix_imx351_snapshot_binning \
    libchromatix_imx351_snapshot_raw_hdr \
    libchromatix_imx351_video_4k \
    libchromatix_imx351_video_binning \
    libchromatix_imx351_zsl_preview_3a \
    libchromatix_imx351_zsl_video_3a \
    libchromatix_s5k3m3_4k_preview_3a \
    libchromatix_s5k3m3_4k_video_3a \
    libchromatix_s5k3m3_common \
    libchromatix_s5k3m3_cpp_hfr_120 \
    libchromatix_s5k3m3_cpp_hfr_60 \
    libchromatix_s5k3m3_cpp_liveshot \
    libchromatix_s5k3m3_cpp_liveshot_raw_hdr \
    libchromatix_s5k3m3_cpp_preview \
    libchromatix_s5k3m3_cpp_snapshot \
    libchromatix_s5k3m3_cpp_snapshot_raw_hdr \
    libchromatix_s5k3m3_cpp_video \
    libchromatix_s5k3m3_default_preview_3a \
    libchromatix_s5k3m3_default_video \
    libchromatix_s5k3m3_default_video_3a \
    libchromatix_s5k3m3_flash_food_cpp \
    libchromatix_s5k3m3_flash_snapshot_cpp \
    libchromatix_s5k3m3_food_preview \
    libchromatix_s5k3m3_food_preview_cpp \
    libchromatix_s5k3m3_food_snapshot \
    libchromatix_s5k3m3_food_snapshot_cpp \
    libchromatix_s5k3m3_hfr_120 \
    libchromatix_s5k3m3_hfr_120_3a \
    libchromatix_s5k3m3_hfr_60 \
    libchromatix_s5k3m3_hfr_60_3a \
    libchromatix_s5k3m3_panorama_3a \
    libchromatix_s5k3m3_panorama_cpp \
    libchromatix_s5k3m3_postproc \
    libchromatix_s5k3m3_preview \
    libchromatix_s5k3m3_preview_raw_hdr_3a \
    libchromatix_s5k3m3_snapshot \
    libchromatix_s5k3m3_snapshot_raw_hdr \
    libchromatix_s5k3m3_zsl_preview_3a \
    libchromatix_s5k3m3_zsl_video_3a \
    libcinemaeffect \
    libdepthmapwrapper \
    libfilm_emulation \
    libfilm_emulation_symphony \
    libflash_pmic \
    libhal_dbg \
    libjpegdhw \
    libjpegdmahw \
    libjpegehw \
    liblg_ae_parameter_4k_preview_hi553 \
    liblg_ae_parameter_4k_preview_imx351 \
    liblg_ae_parameter_4k_preview_s5k3m3 \
    liblg_ae_parameter_4k_video_hi553 \
    liblg_ae_parameter_4k_video_imx351 \
    liblg_ae_parameter_4k_video_s5k3m3 \
    liblg_ae_parameter_binning_4k_imx351 \
    liblg_ae_parameter_binning_video_imx351 \
    liblg_ae_parameter_binning_zsl_imx351 \
    liblg_ae_parameter_default_preview_hi553 \
    liblg_ae_parameter_default_preview_imx351 \
    liblg_ae_parameter_default_preview_s5k3m3 \
    liblg_ae_parameter_default_video_hi553 \
    liblg_ae_parameter_default_video_imx351 \
    liblg_ae_parameter_default_video_s5k3m3 \
    liblg_ae_parameter_face_unlock_hi553 \
    liblg_ae_parameter_hdr_snapshot_imx351 \
    liblg_ae_parameter_hdr_snapshot_s5k3m3 \
    liblg_ae_parameter_hdr_video_imx351 \
    liblg_ae_parameter_hdr_video_s5k3m3 \
    liblg_ae_parameter_hfr_120_imx351 \
    liblg_ae_parameter_hfr_120_s5k3m3 \
    liblg_ae_parameter_hfr_240_imx351 \
    liblg_ae_parameter_hfr_60_imx351 \
    liblg_ae_parameter_hfr_60_s5k3m3 \
    liblg_ae_parameter_hfr_90_imx351 \
    liblg_ae_parameter_hfr_90_s5k3m3 \
    liblg_ae_parameter_panorama_imx351 \
    liblg_ae_parameter_panorama_s5k3m3 \
    liblg_ae_parameter_raw_hdr_imx351 \
    liblg_ae_parameter_raw_hdr_s5k3m3 \
    liblg_ae_parameter_vt_hi553 \
    liblg_ae_parameter_zsl_preview_hi553 \
    liblg_ae_parameter_zsl_preview_imx351 \
    liblg_ae_parameter_zsl_preview_s5k3m3 \
    liblg_ae_parameter_zsl_video_hi553 \
    liblg_ae_parameter_zsl_video_imx351 \
    liblg_ae_parameter_zsl_video_s5k3m3 \
    liblg_awb_parameter_hi553_4k_preview \
    liblg_awb_parameter_hi553_4k_video \
    liblg_awb_parameter_hi553_default_preview \
    liblg_awb_parameter_hi553_default_video \
    liblg_awb_parameter_hi553_face_unlock \
    liblg_awb_parameter_hi553_vt \
    liblg_awb_parameter_hi553_zsl_preview \
    liblg_awb_parameter_hi553_zsl_video \
    liblg_awb_parameter_imx351_4k_preview \
    liblg_awb_parameter_imx351_4k_video \
    liblg_awb_parameter_imx351_binning_4k \
    liblg_awb_parameter_imx351_binning_video \
    liblg_awb_parameter_imx351_binning_zsl \
    liblg_awb_parameter_imx351_default_preview \
    liblg_awb_parameter_imx351_default_video \
    liblg_awb_parameter_imx351_hdr_snapshot \
    liblg_awb_parameter_imx351_hdr_video \
    liblg_awb_parameter_imx351_hfr_120 \
    liblg_awb_parameter_imx351_hfr_240 \
    liblg_awb_parameter_imx351_hfr_60 \
    liblg_awb_parameter_imx351_hfr_90 \
    liblg_awb_parameter_imx351_panorama \
    liblg_awb_parameter_imx351_raw_hdr \
    liblg_awb_parameter_imx351_zsl_preview \
    liblg_awb_parameter_imx351_zsl_video \
    liblg_awb_parameter_s5k3m3_4k_preview \
    liblg_awb_parameter_s5k3m3_4k_video \
    liblg_awb_parameter_s5k3m3_default_preview \
    liblg_awb_parameter_s5k3m3_default_video \
    liblg_awb_parameter_s5k3m3_hdr_snapshot \
    liblg_awb_parameter_s5k3m3_hdr_video \
    liblg_awb_parameter_s5k3m3_hfr_120 \
    liblg_awb_parameter_s5k3m3_hfr_60 \
    liblg_awb_parameter_s5k3m3_hfr_90 \
    liblg_awb_parameter_s5k3m3_panorama \
    liblg_awb_parameter_s5k3m3_raw_hdr \
    liblg_awb_parameter_s5k3m3_zsl_preview \
    liblg_awb_parameter_s5k3m3_zsl_video \
    liblgae_main \
    liblgaf_core \
    liblgawb_main \
    liblgcamera_beautypreview \
    liblgcine_core \
    liblgdnn \
    liblghdri \
    liblgmda \
    libllvm-qcom \
    libmm-qcamera \
    libmmcamera2_c2d_module \
    libmmcamera2_cpp_module \
    libmmcamera2_iface_modules \
    libmmcamera2_imglib_modules \
    libmmcamera2_isp_modules \
    libmmcamera2_mct \
    libmmcamera2_mct_shimlayer \
    libmmcamera2_pp_buf_mgr \
    libmmcamera2_pproc_modules \
    libmmcamera2_q3a_core \
    libmmcamera2_sensor_modules \
    libmmcamera2_stats_modules \
    libmmcamera_bokeh \
    libmmcamera_depth_map \
    libmmcamera_dummyalgo \
    libmmcamera_eebinparse \
    libmmcamera_eeprom_util \
    libmmcamera_eztune_module \
    libmmcamera_facedetection_lib \
    libmmcamera_hdr_gb_lib \
    libmmcamera_hi553 \
    libmmcamera_hi553_brcf016gwz_eeprom \
    libmmcamera_hvx_add_constant \
    libmmcamera_hvx_grid_sum \
    libmmcamera_imglib \
    libmmcamera_imglib_faceproc_adspstub \
    libmmcamera_imx351 \
    libmmcamera_imx351_m24c64m_eeprom \
    libmmcamera_interface \
    libmmcamera_isp_abf48 \
    libmmcamera_isp_aec_bg_stats47 \
    libmmcamera_isp_bf_stats47 \
    libmmcamera_isp_bg_stats46 \
    libmmcamera_isp_bhist_stats44 \
    libmmcamera_isp_black_level48 \
    libmmcamera_isp_bpc48 \
    libmmcamera_isp_cac47 \
    libmmcamera_isp_chroma_enhan40 \
    libmmcamera_isp_chroma_suppress40 \
    libmmcamera_isp_clamp_encoder40 \
    libmmcamera_isp_clamp_video40 \
    libmmcamera_isp_clamp_viewfinder40 \
    libmmcamera_isp_color_correct46 \
    libmmcamera_isp_color_xform_encoder46 \
    libmmcamera_isp_color_xform_video46 \
    libmmcamera_isp_color_xform_viewfinder46 \
    libmmcamera_isp_cs_stats46 \
    libmmcamera_isp_demosaic48 \
    libmmcamera_isp_demux48 \
    libmmcamera_isp_fovcrop_encoder46 \
    libmmcamera_isp_fovcrop_video46 \
    libmmcamera_isp_fovcrop_viewfinder46 \
    libmmcamera_isp_gamma44 \
    libmmcamera_isp_gic48 \
    libmmcamera_isp_gtm46 \
    libmmcamera_isp_hdr48 \
    libmmcamera_isp_hdr_be_stats46 \
    libmmcamera_isp_hdr_bhist_stats44 \
    libmmcamera_isp_ihist_stats46 \
    libmmcamera_isp_linearization40 \
    libmmcamera_isp_ltm47 \
    libmmcamera_isp_luma_adaptation40 \
    libmmcamera_isp_mce40 \
    libmmcamera_isp_mesh_rolloff44 \
    libmmcamera_isp_pdaf48 \
    libmmcamera_isp_pedestal_correct46 \
    libmmcamera_isp_rs_stats46 \
    libmmcamera_isp_scaler_encoder46 \
    libmmcamera_isp_scaler_video46 \
    libmmcamera_isp_scaler_viewfinder46 \
    libmmcamera_isp_sce40 \
    libmmcamera_isp_snr47 \
    libmmcamera_isp_sub_module \
    libmmcamera_paaf_lib \
    libmmcamera_pdaf \
    libmmcamera_pdafcamif \
    libmmcamera_ppbase_module \
    libmmcamera_ppeiscore \
    libmmcamera_quadracfa \
    libmmcamera_s5k3m3 \
    libmmcamera_s5k3m3_brcb032gwz_eeprom \
    libmmcamera_sw2d_lib \
    libmmcamera_thread_services \
    libmmcamera_tuning \
    libmmcamera_tuning_lookup \
    libmmjpeg \
    libmmjpeg_interface \
    libmmlib2d_interface \
    libmmqjpeg_codec \
    libmmqjpegdma \
    libmorpho_image_stab31 \
    libmorpho_superzoom \
    libmpbase \
    libois_bu24333gwl \
    libois_bu63165 \
    libois_lc898122 \
    libois_renesascl \
    libqcbor \
    libqomx_core \
    libqomx_jpegdec \
    libqomx_jpegenc \
    libqomx_jpegenc_pipe \
    libremosaic_daemon \
    libsmwrapper \
    libsymphony-1.1.2 \
    libsymphony-1.1.4 \
    libsymphonypower-1.1.2 \
    libsymphonypower-1.1.4 \
    com.qualcomm.qti.dpm.api@1.0_vendor \
    android.hardware.bluetooth@1.0-impl-qti \
    com.dsi.ant@1.0-impl \
    fingerprint.msm8998 \
    gatekeeper.msm8998 \
    keystore.msm8998 \
    vendor.qti.esepowermanager@1.1-impl \
    vendor.qti.gnss@4.0-impl \
    vendor.qti.hardware.alarm@1.0-impl \
    vendor.qti.hardware.bluetooth_sar@1.1-impl \
    vendor.qti.hardware.btconfigstore@2.0-impl \
    vendor.qti.hardware.fm@1.0-impl \
    vendor.qti.hardware.qccvndhal@1.0-impl \
    vendor.qti.hardware.qseecom@1.0-impl \
    vendor.qti.hardware.qteeconnector@1.0-impl \
    vendor.qti.hardware.soter@1.0-impl \
    vulkan.msm8998 \
    libGPQTEEC_vendor \
    libGPTEE_vendor \
    libGPreqcancel \
    libGPreqcancel_svc \
    libQSEEComAPI \
    libQTEEConnector_vendor \
    libSecureUILib \
    libStDrvInt \
    libasn1cper \
    libasn1crt \
    libasn1crtx \
    libbase64 \
    libbt-hidlclient \
    libbtnv \
    libcdfw \
    libcdfw_remote_api \
    libcne \
    libcneapiclient \
    libcneoplookup \
    libconfigdb \
    libcpion \
    libdataitems \
    libdisp-aba \
    libdpmqmihal \
    libdrmfs \
    libdrmtime \
    libdsi_netctrl \
    libgdtap \
    libhdcp1prov \
    libhdcp2p2prov \
    libhdcpsrm \
    libhdr_tm \
    libizat_client_api \
    libizat_core \
    liblbs_core \
    libloc_api_v02 \
    libloc_socket \
    liblocationservice \
    liblocationservice_glue \
    liblowi_client \
    liblqe \
    libminksocket \
    libmm-hdcpmgr \
    libnetmgr \
    libnetmgr_common \
    libnetmgr_nr_fusion \
    libnetmgr_rmnet_ext \
    libnlnetmgr \
    libpdmapper \
    libpdnotifier \
    libperipheral_client \
    libqcc_file_agent \
    libqcmaputils \
    libqcrilFramework \
    libqcrildatactl \
    libqisl \
    libqrtr \
    libqseed3 \
    libqsocket \
    libril-qc-hal-qmi \
    libril-qc-logger \
    libril-qc-ltedirectdisc \
    libril-qc-radioconfig \
    libril-qcril-hook-oem \
    librilqmiservices \
    librmp \
    librpmb \
    libsdedrm \
    libsdm-color \
    libsdm-diag \
    libsdmextension \
    libsecureui_svcsock \
    libsettings \
    libspl \
    libssd \
    libsystem_health_mon \
    libthermalioctl \
    libtinyxml2_1 \
    libtzdrmgenprov \
    libwms \
    libwqe \
    libwvhidl \
    libxml \
    libxtadapter \
    libxtwifi_server_protocol \
    libxtwifi_server_protocol_uri_v3 \
    qcrild_librilutils \
    qtibus \
    qtimutex \
    vendor.display.color@1.0 \
    vendor.display.color@1.1 \
    vendor.display.color@1.2 \
    vendor.display.postproc@1.0 \
    vendor.qti.data.factory@2.0 \
    vendor.qti.data.factory@2.1 \
    vendor.qti.data.factory@2.2 \
    vendor.qti.data.factory@2.3 \
    vendor.qti.data.mwqem@1.0 \
    vendor.qti.data.slm@1.0 \
    vendor.qti.esepowermanager@1.0 \
    vendor.qti.esepowermanager@1.1 \
    vendor.qti.gnss@1.0 \
    vendor.qti.gnss@1.1 \
    vendor.qti.gnss@1.2 \
    vendor.qti.gnss@2.0 \
    vendor.qti.gnss@2.1 \
    vendor.qti.gnss@3.0 \
    vendor.qti.gnss@4.0-service \
    vendor.qti.gnss@4.0 \
    vendor.qti.hardware.alarm@1.0 \
    vendor.qti.hardware.bluetooth_sar@1.0 \
    vendor.qti.hardware.bluetooth_sar@1.1 \
    vendor.qti.hardware.data.cne.internal.api@1.0 \
    vendor.qti.hardware.data.cne.internal.constants@1.0 \
    vendor.qti.hardware.data.cne.internal.server@1.0 \
    vendor.qti.hardware.data.connection@1.0 \
    vendor.qti.hardware.data.connection@1.1 \
    vendor.qti.hardware.data.dynamicdds@1.0 \
    vendor.qti.hardware.data.iwlan@1.0 \
    vendor.qti.hardware.data.latency@1.0 \
    vendor.qti.hardware.data.lce@1.0 \
    vendor.qti.hardware.data.qmi@1.0 \
    vendor.qti.hardware.fm@1.0_vendor \
    vendor.qti.hardware.mwqemadapter@1.0 \
    vendor.qti.hardware.qccsyshal@1.0_vendor \
    vendor.qti.hardware.qccvndhal@1.0-halimpl \
    vendor.qti.hardware.qccvndhal@1.0_vendor \
    vendor.qti.hardware.qseecom@1.0 \
    vendor.qti.hardware.qteeconnector@1.0 \
    vendor.qti.hardware.radio.am@1.0 \
    vendor.qti.hardware.radio.ims@1.0 \
    vendor.qti.hardware.radio.ims@1.1 \
    vendor.qti.hardware.radio.ims@1.2 \
    vendor.qti.hardware.radio.ims@1.3 \
    vendor.qti.hardware.radio.ims@1.4 \
    vendor.qti.hardware.radio.ims@1.5 \
    vendor.qti.hardware.radio.ims@1.6 \
    vendor.qti.hardware.radio.ims@1.7 \
    vendor.qti.hardware.radio.internal.deviceinfo@1.0 \
    vendor.qti.hardware.radio.lpa@1.0 \
    vendor.qti.hardware.radio.lpa@1.1 \
    vendor.qti.hardware.radio.qcrilhook@1.0 \
    vendor.qti.hardware.radio.qtiradio@1.0 \
    vendor.qti.hardware.radio.qtiradio@2.0 \
    vendor.qti.hardware.radio.qtiradio@2.1 \
    vendor.qti.hardware.radio.qtiradio@2.2 \
    vendor.qti.hardware.radio.qtiradio@2.3 \
    vendor.qti.hardware.radio.qtiradio@2.4 \
    vendor.qti.hardware.radio.uim@1.0 \
    vendor.qti.hardware.radio.uim@1.1 \
    vendor.qti.hardware.radio.uim@1.2 \
    vendor.qti.hardware.radio.uim_remote_client@1.0 \
    vendor.qti.hardware.radio.uim_remote_client@1.1 \
    vendor.qti.hardware.radio.uim_remote_client@1.2 \
    vendor.qti.hardware.radio.uim_remote_server@1.0 \
    vendor.qti.hardware.soter@1.0 \
    vendor.qti.hardware.tui_comm@1.0 \
    vendor.qti.ims.rcsconfig@1.0 \
    vendor.qti.ims.rcsconfig@1.1 \
    vendor.qti.ims.rcsconfig@2.0 \
    vendor.qti.ims.rcsconfig@2.1 \
    vendor.qti.latency@2.0 \
    vendor.qti.latency@2.1 \
    AlacDecoderModule.so \
    ApeDecoderModule.so \
    AudioSphereModule.so \
    CFCMModule.so \
    DTS_HPX_MODULE.so \
    DolbyMobileModule.so \
    DolbySurroundModule.so \
    EtsiAmrWbPlusDecModule.so \
    EtsiEaacPlusEncAndCmnModule.so \
    FlacDecoderModule.so \
    HeaacDecoderModule.so \
    HpMp2DecoderModule.so \
    SAPlusCmnModule.so \
    VorbisDecoderModule.so \
    WmaProDecoderModule.so \
    WmaStdDecoderModule.so \
    capi_v2_aptX_Classic \
    capi_v2_aptX_HD \
    fastrpc_shell_0 \
    fluence_voiceplus_module.so \
    libFastRPC_AUE_Forward_skel \
    libFastRPC_UTF_Forward_Qtc2_skel \
    libFastRPC_UTF_Forward_skel \
    libadsp_fd_skel \
    libadsp_hvx_add_constant \
    libadsp_hvx_skel \
    libapps_mem_heap \
    libc++.so \
    libc++abi.so \
    libdspCV_skel \
    libfastcvadsp \
    libfastcvadsp_skel \
    libscveBlobDescriptor_skel \
    libscveT2T_skel \
    libsns_low_lat_stream_skel \
    libstability_skel \
    libsysmon_skel \
    libsysmondomain_skel \
    libvpp_frc \
    libvpp_svc_skel \
    mmecns_module.so \
    com.qualcomm.qti.dpm.api@1.0 \
    fm_helium \
    libdiag_system \
    libdpmctmgr \
    libdpmfdmgr \
    libdpmframework \
    libdpmtcm \
    libfm-hci \
    libqcc \
    libqcc_file_agent_sys \
    vendor.qti.diaghal@1.0 \
    vendor.qti.hardware.fm@1.0 \
    vendor.qti.hardware.qccsyshal@1.0-halimpl \
    vendor.qti.hardware.qccsyshal@1.0 \
    vendor.qti.hardware.qccvndhal@1.0 \
    CneApp \
    IWlanService \
    HotwordEnrollmentOKGoogleHEXAGON \
    HotwordEnrollmentXGoogleHEXAGON \
    QtiTelephonyService \
    dpmserviceapp \
    qcrilmsgtunnel \
    com.qti.dpmframework \
    dpmapi \
    qcrilhook \
    vendor.qti.hardware.alarm-V1.0-java \
    manifest_android.hardware.drm@1.3-service.widevine.xml \
    vendor.qti.gnss@4.0-service.xml \
    adpl \
    adsprpcd \
    cnd \
    cnss-daemon \
    dpmQmiMgr \
    hvdcp_opti \
    android.hardware.bluetooth@1.0-service-qti \
    android.hardware.drm@1.3-service.widevine \
    qcrild \
    vendor.display.color@1.0-service \
    vendor.lge.hardware.biometrics.fingerprint@2.1-service \
    vendor.qti.esepowermanager@1.1-service \
    vendor.qti.hardware.alarm@1.0-service \
    vendor.qti.hardware.qseecom@1.0-service \
    vendor.qti.hardware.qteeconnector@1.0-service \
    vendor.qti.hardware.soter@1.0-service \
    vendor.qti.hardware.tui_comm@1.0-service-qti \
    irsc_util \
    loc_launcher \
    lowi-server \
    mlid \
    mm-qcamera-app \
    netmgrd \
    pd-mapper \
    pm-proxy \
    pm-service \
    power_off_alarm \
    qni \
    qrtr-cfg \
    qrtr-lookup \
    qrtr-ns \
    qseecomd \
    qti \
    rmt_storage \
    sensors.qti \
    tftp_server \
    thermal-engine \
    vendor.qti.hardware.soter@1.0-provision \
    xtra-daemon \
    xtwifi-client \
    xtwifi-inet-agent \
    dpmd
